### PR TITLE
Use document as the scroll parent if the body is the scroll parent

### LINKED ISSUE #116: Autoscroll reposition bugs
https://github.com/jgwhite/ember-sortable/pull/104
@tim-evans 
Issue with autoscroll merge. Create a list of 100 items or so, scroll down to near the bottom. Grab and item to sort. Scroll up a bit and try sorting another item, the scroll position automatically jumps to the position of the last object that was moved.

Also autoscroll to the top of the screen doesn't seem to work. Only to bottom.

### PR DESCRIPTION
**Pull request by tim-evans**
Fix #116 by using the document instead of the body element as the scroll parent.

### CODE REVIEW

**Comment by tim-evans** [comment]
Poke!

**Comment by acburdine** [comment]
Apologies @tim-evans, completely forgot about this! I'll do my best to get it tested tonight and merged. Will release a 1.9.1 this weekend :)

**Comment by acburdine** [comment]
Ok - tested this and it works :) thanks for the PR @tim-evans!

**Comment by tim-evans** [comment]
👍

**Pull request merged**
