### PR TITLE
Upgrade ember-cli to 0.2.7

### PR DESCRIPTION
**Pull request by jgwhite**

### CODE REVIEW

**Comment by jgwhite** [comment]
@jmurphyau this is a bit cheeky, but would you mind sanity checking this for me? :grin:

**Comment by jmurphyau** [comment]
looks good to me (:

**Comment by jmurphyau** [comment]
Are you going to release an update with the last few PRs merged? Or are you waiting to put a few other things in before doing a new version? Keen to start using this

**Comment by jgwhite** [comment]
Gonna release right now :grinning:

**Comment by jgwhite** [comment]
And released…

**Comment by jmurphyau** [comment]
awesome

**Pull request merged**
