### PR TITLE
ember-cli-htmlbars 2.0.3

### PR DESCRIPTION
**Pull request by Dhaulagiri**

### CODE REVIEW

**Comment by jgwhite** [comment]
Could you rebase this one? Thanks!

**Comment by Dhaulagiri** [comment]
@jgwhite done!

**Comment by jgwhite** [comment]
Thanks!

**Comment by jgwhite** [comment]
Released in [1.11.2](https://github.com/jgwhite/ember-sortable/releases/tag/v1.11.2)

**Pull request merged**
