### PR TITLE
Distinguish between clicking and dragging an item

### PR DESCRIPTION
**Pull request by opsb**
PR to solve https://github.com/jgwhite/ember-sortable/issues/50. 

This delays the start of a drag until the mouse is moved. If a drag is completed it also prevents a click from being fired on the item that's just been dragged.

I'm afraid there's no tests included, not sure how to test drag n drop. I can circle back but I need to take a look at denzo's fork https://github.com/denzo/ember-sortable and get dragging between lists working within my app as a first priority (currently swapping out an existing component that used jquery-ui-sortable). 

For manual testing I've introduced an {{item-presenter item=item}} component, which reports 'Item clicked' to the console when it's clicked, and added it to the horizontal demo. When an item is dragged you'll see 'Updated'. You should see that they're now mutually exclusive.

I've tested in IE(9), chrome(latest), safari(latest) and firefox(latest).

### CODE REVIEW

**Comment by opsb** [comment]
Possible library for testing drag events https://github.com/bitovi/syn

**Comment by jgwhite** [comment]
This is perfect, thanks so much. I like the approach you took with verifying behaviour. Now that component integration tests have arrived we'll be using them in the suite.

**Comment by jgwhite** [comment]
Going to test this out when I'm back in front of a machine but the code looks spot on. Could you squash to one commit?

**Comment by opsb** [comment]
@jgwhite Squashed. There's a little simplification that makes use of bind, I'm guessing this is reasonable as IE9+ supports bind and IE8 doesn't support 2D transforms. However I can back this out if you can imagine a scenario where someone might use a polyfill to add the 2D transforms.

**Comment by jgwhite** [comment]
Given that Ember 2.0 will no longer support IE8, I’m happy to proceed with `bind`.

**Comment by jgwhite** [comment]
Released as v1.5.1

**Comment by mehulkar** [comment]
beautiful people. thanks @opsb!

**Pull request merged**
