### PR TITLE
Add distance attribute, for when sorting should start

### PR DESCRIPTION
**Pull request by mupkoo**
I took a different approach from the existing PR. With this PR, the drag functionality is not registered until the node is dragged more than the passed distance.

Let me know if you have any comments.

### CODE REVIEW

**Comment by mupkoo** [comment]
I will add an acceptance test for the `distance` attribute, to make sure that the helpers are working as well.

**Comment by mupkoo** [comment]
@cspanring I think this is ready for review. If you think it's ok, I will squash the commits so you can merge it.

Thank you

**Comment by cspanring** [comment]
@mupkoo did you mean to ping me? I had a really minor contribution to this repo and am not sure if I'm the right person to review your PR...

**Comment by mupkoo** [comment]
My bad :) I wanted to ping @acburdine

**Comment by acburdine** [comment]
Thanks @mupkoo! I will get this looked at later today 😄

**Pull request merged**
