### PR TITLE
Ignore right-click (and ctrl-click on OS X)

### LINKED ISSUE #63: Disable on right click
Right click currently starts drag.  I'm constantly hitting it when I try to inspect element in Chrome.

### PR DESCRIPTION
**Pull request by jgwhite**
Closes #63

### CODE REVIEW

**Comment by jgwhite** [comment]
@jgadbois this should address your issue. Mind giving it a sanity check for me?

**Comment by jgwhite** [comment]
Would be good to add a test for this but would entail extending capabilities of the `drag` test helper and time is short.

**Comment by jgwhite** [comment]
Tests are also failing on master. Not sure why yet.

**Comment by jgadbois** [comment]
Trying it out now

**Comment by jgwhite** [comment]
Tests are green. Let me know what you reckon.

**Comment by jgadbois** [comment]
Working fine for me, thanks!

**Comment by jgwhite** [comment]
Cool, thanks! Will cut a new release shortly.

**Pull request merged**
